import json
from deep_translator import GoogleTranslator
import time
import re

# All keys that need to be translated
KEYS = [
    'Profile', 'Gaze', 'Handwriting', 'Phonics', 'Results',
    'Child\'s profile',
    'This helps us personalise the screening and compare results against age-appropriate norms.',
    'Child\'s first name', 'e.g. Arjun', 'Date of birth', 'within screening range ✓',
    'Gender', 'Male', 'Female', 'Other', 'Primary language', 'Continue to screening',
    'Want to see a sample result first?', 'Load demo — Arjun, age 7 →', 'Back',
    'Gaze tracking task',
    'will see two images side by side — a face and a pattern. We\'ll track where their eyes move using the front camera. The task takes 30 seconds.',
    'Allow camera access when prompted', 'Make sure the room is well lit',
    'Hold the screen at eye level for the child', 'Minimise distractions around them',
    'Start gaze task', 'Starting camera...', 'Recording gaze...',
    'Human face', 'Geometric pattern', 'Face attention', 'Object attention',
    'Gaze task complete', 'Here\'s what we observed in', 'the child', 'gaze pattern.',
    '⚠ Reduced social attention detected', '✓ Social attention within normal range',
    'spent', 'of time looking at the geometric pattern vs',
    'on the face. Typically developing children prefer faces. This pattern is associated with ASD social attention differences.',
    'showed a typical social attention pattern, preferring to look at the human face over the geometric pattern.',
    'Continue to handwriting task →',
    'Clear', 'Done', 'Yes', 'No', 'Example', 'LEFT', 'RIGHT', 'Write the letter',
    'Write the lowercase letter as you normally would.',
    'Handwriting complete', 'out of', 'letters showed reversal patterns.',
    'Reversed', 'Correct', '⚠ Letter reversals detected', '✓ Letter formation within normal range',
    'reversal rate. This pattern is associated with phonological dyslexia and dysgraphia.',
    'Letter formation appears typical for this age group.',
    'Continue to phonics task', 'Do these words rhyme?', 'Listen carefully and tap Yes or No.',
    '🔊 Hear the words again', 'Phonics task complete', 'Continue to Sparky task →', 'correct',
    'Below expected range — phonological processing difficulty detected',
    'Within expected range for this age group',
    'Neurodevelopmental Screening Report', 'Child', 'Age', 'Language', 'Date',
    'IMPORTANT: This is a screening tool, not a clinical diagnosis. Please consult a qualified specialist for a full assessment.',
    'SCREENING RESULTS', 'ASD Social Communication', 'ASD Repetitive Behaviour',
    'Dyslexia', 'Dysgraphia', 'Dyscalculia', 'HIGH CONCERN', 'MODERATE', 'LOW CONCERN',
    'DYSLEXIA TYPE:', 'Phonological', 'Surface', 'Rapid Naming', 'Visual',
    'STUDY TECHNIQUES', 'CLASSROOM ACCOMMODATIONS', 'RECOMMENDED DAILY ACTIVITY SCHEDULE',
    'NEXT STEPS', '1. Share this report with your child\'s class teacher immediately',
    '2. Book an appointment with a qualified child psychologist for full assessment',
    '3. Re-screen on NeuroSpark in 30 days to track progress',
    '4. Join a parent support group — connect with other families',
    'Generated by NeuroSpark · Free neurodevelopmental screening · neurospark.app',
    'Computing results...'
]

LANGUAGES = {
    'English': 'en',
    'Hindi': 'hi',
    'Kannada': 'kn',
    'Tamil': 'ta',
    'Telugu': 'te',
    'Marathi': 'mr',
    'Bengali': 'bn',
    'Gujarati': 'gu',
    'Punjabi': 'pa',
    'Malayalam': 'ml',
    'Odia': 'or',
    'Assamese': 'as'
}

def escape_string(s):
    # Escape single quotes and backslashes for writing to JS
    return s.replace('\\', '\\\\').replace("'", "\\'")

def run():
    print("Starting translation...")
    translations = {'English': {k: k for k in KEYS}}
    
    for lang_name, lang_code in LANGUAGES.items():
        if lang_name == 'English': continue
        print(f"Translating {lang_name}...")
        translator = GoogleTranslator(source='en', target=lang_code)
        lang_dict = {}
        for key in KEYS:
            try:
                translated = translator.translate(key)
                lang_dict[key] = translated
                time.sleep(0.1) # tiny sleep to avoid rate limits
            except Exception as e:
                print(f"Error on {key}: {e}")
                lang_dict[key] = key # fallback
        translations[lang_name] = lang_dict

    # Write JS file
    js_content = "export const translations = {\n"
    for lang, dic in translations.items():
        js_content += f"  {lang}: {{\n"
        for k, v in dic.items():
            js_content += f"    '{escape_string(k)}': '{escape_string(v)}',\n"
        js_content += "  },\n"
    js_content += "}\n\n"
    js_content += "export function tGlobal(key, lang) {\n"
    js_content += "  if (!lang || lang === 'English') return key\n"
    js_content += "  const dict = translations[lang]\n"
    js_content += "  if (!dict) return key\n"
    js_content += "  return dict[key] || key\n"
    js_content += "}\n"

    target_path = r"c:\Users\riddh\Downloads\NeuroSpark-Complete_zip\NeuroSpark-Complete\neurospark\src\utils\translations.js"
    with open(target_path, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print("Successfully wrote translations.js")

if __name__ == '__main__':
    run()
