import fs from 'fs';
import { translate } from '@vitalets/google-translate-api';

const KEYS = [
  'Profile', 'Gaze', 'Handwriting', 'Phonics', 'Results',
  "Child's profile",
  'This helps us personalise the screening and compare results against age-appropriate norms.',
  "Child's first name", 'e.g. Arjun', 'Date of birth', 'within screening range ✓',
  'Gender', 'Male', 'Female', 'Other', 'Primary language', 'Continue to screening',
  'Want to see a sample result first?', 'Load demo — Arjun, age 7 →', 'Back',
  'Gaze tracking task',
  "will see two images side by side — a face and a pattern. We'll track where their eyes move using the front camera. The task takes 30 seconds.",
  'Allow camera access when prompted', 'Make sure the room is well lit',
  'Hold the screen at eye level for the child', 'Minimise distractions around them',
  'Start gaze task', 'Starting camera...', 'Recording gaze...',
  'Human face', 'Geometric pattern', 'Face attention', 'Object attention',
  'Gaze task complete', "Here's what we observed in", 'the child', 'gaze pattern.',
  '⚠ Reduced social attention detected', '✓ Social attention within normal range',
  'spent', 'of time looking at the geometric pattern vs',
  'on the face. Typically developing children prefer faces. This pattern is associated with ASD social attention differences.',
  'showed a typical social attention pattern, preferring to look at the human face over the geometric pattern.',
  'Continue to handwriting task →',
  'Clear', 'Done', 'Yes', 'No', 'Example', 'LEFT', 'RIGHT', 'Write the letter',
  'Write the lowercase letter as you normally would.',
  'Handwriting complete', 'out of', 'letters showed reversal patterns.',
  'Reversed', 'Correct', '⚠ Letter reversals detected', '✓ Letter formation within normal range',
  'reversal rate. This pattern is associated with phonological dyslexia and dysgraphia.',
  'Letter formation appears typical for this age group.',
  'Continue to phonics task', 'Do these words rhyme?', 'Listen carefully and tap Yes or No.',
  '🔊 Hear the words again', 'Phonics task complete', 'Continue to Sparky task →', 'correct',
  'Below expected range — phonological processing difficulty detected',
  'Within expected range for this age group',
  'Neurodevelopmental Screening Report', 'Child', 'Age', 'Language', 'Date',
  'IMPORTANT: This is a screening tool, not a clinical diagnosis. Please consult a qualified specialist for a full assessment.',
  'SCREENING RESULTS', 'ASD Social Communication', 'ASD Repetitive Behaviour',
  'Dyslexia', 'Dysgraphia', 'Dyscalculia', 'HIGH CONCERN', 'MODERATE', 'LOW CONCERN',
  'DYSLEXIA TYPE:', 'Phonological', 'Surface', 'Rapid Naming', 'Visual',
  'STUDY TECHNIQUES', 'CLASSROOM ACCOMMODATIONS', 'RECOMMENDED DAILY ACTIVITY SCHEDULE',
  'NEXT STEPS', "1. Share this report with your child's class teacher immediately",
  '2. Book an appointment with a qualified child psychologist for full assessment',
  '3. Re-screen on NeuroSpark in 30 days to track progress',
  '4. Join a parent support group — connect with other families',
  'Generated by NeuroSpark · Free neurodevelopmental screening · neurospark.app',
  'Computing results...'
];

const LANGUAGES = {
  English: 'en',
  Hindi: 'hi',
  Kannada: 'kn',
  Tamil: 'ta',
  Telugu: 'te',
  Marathi: 'mr',
  Bengali: 'bn',
  Gujarati: 'gu',
  Punjabi: 'pa',
  Malayalam: 'ml',
  Odia: 'or',
  Assamese: 'as'
};

const escapeString = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

async function run() {
  console.log("Starting translation script...");
  const translations = { English: {} };
  for (const k of KEYS) translations.English[k] = k;

  for (const [langName, langCode] of Object.entries(LANGUAGES)) {
    if (langName === 'English') continue;
    console.log(`Translating to ${langName}...`);
    translations[langName] = {};
    for (const key of KEYS) {
      try {
        const { text } = await translate(key, { to: langCode });
        translations[langName][key] = text;
      } catch (err) {
        console.error(`Failed to translate "${key}" to ${langName}:`, err.message);
        translations[langName][key] = key; // fallback
      }
      // brief delay
      await new Promise(r => setTimeout(r, 50));
    }
  }

  let jsContent = "export const translations = {\n";
  for (const [lang, dic] of Object.entries(translations)) {
    jsContent += `  ${lang}: {\n`;
    for (const [k, v] of Object.entries(dic)) {
      jsContent += `    '${escapeString(k)}': '${escapeString(v)}',\n`;
    }
    jsContent += "  },\n";
  }
  jsContent += "}\n\n";
  jsContent += "export function tGlobal(key, lang) {\n";
  jsContent += "  if (!lang || lang === 'English') return key\n";
  jsContent += "  const dict = translations[lang]\n";
  jsContent += "  if (!dict) return key\n";
  jsContent += "  return dict[key] || key\n";
  jsContent += "}\n";

  fs.writeFileSync('./src/utils/translations.js', jsContent, 'utf-8');
  console.log("SUCCESS");
}

run();
